### ISSUE TITLE
Can't find tests inside multiple folders

### ISSUE THREAD

**Issue by msilesgap** [0xIslamTaha/orchestrator#8]
@0xIslamTaha

My folder structure looks like the attached screenshot, above navigation is the folder called integration(src/integration/navigation/tests/)

![Screen Shot 2021-10-14 at 8 40 58 AM](https://user-images.githubusercontent.com/6989239/137340956-777e31e7-73b6-458d-afb8-6dfc68129e67.png)
 
I have added the paths like this

```
"specsHomePath": "src/integration/navigation/tests/**/*.spec.js",
"specsDockerPath": "src/integration/navigation/tests/**/*.spec.js",
```

```
"specsHomePath": "src/integration/navigation/tests/**",
"specsDockerPath": "src/integration/navigation/tests/**",
```

```
  "specsHomePath": "src/integration/navigation",
  "specsDockerPath": "src/integration/navigation",
```

```
  "specsHomePath": "src/integration/navigation/",
  "specsDockerPath": "src/integration/navigation/",
```

but I'm getting the following error

```
moisessiles@msilesMacbook project.tests.cypress % npx orchestrator --config orchestrator.json
START ORCHESTRATOR
report does not exist, are you sure there is a json report in undefined path?
timeout --preserve-status 30m docker-compose -f docker-compose.yml run --name container_25678__0 cypress-container bash -c 'exit_code=0; npx cypress run -b chrome --headless --spec src/integration/navigationpage-classes || exit_code=$? ; pkill -9 cypress ; exit $exit_code'
timeout --preserve-status 30m docker-compose -f docker-compose.yml run --name container_30793__1 cypress-container bash -c 'exit_code=0; npx cypress run -b chrome --headless --spec src/integration/navigationtests || exit_code=$? ; pkill -9 cypress ; exit $exit_code'
Creating projecttestscypress_cypress-container_run ... 
Creating projecttestscypress_cypress-container_run ... 
Creating projecttestscypress_cypress-container_run ... done
Creating projecttestscypress_cypress-container_run ... done
Can't run because no spec files were found.

We searched for any files matching this glob pattern:

src/integration/navigationtests

Relative to the project root folder:

/orechestrator_usecase
Can't run because no spec files were found.

We searched for any files matching this glob pattern:

src/integration/navigationpage-classes

Relative to the project root folder:

/orechestrator_usecase
1
1
Removing container_30793__1 ... 
Removing container_25678__0 ... 
Removing container_25678__0 ... done
Removing container_30793__1 ... done
generate the report ....
/Users/moisessiles/Downloads/Documents.GAP/GAPProjects/myproject/project.tests.cypress/node_modules/mochawesome-merge/lib/index.js:14
    throw new Error(`Pattern ${pattern} matched no report files`)
          ^

Error: Pattern cypress/report/mochawesome-report/*.json matched no report files
    at /Users/moisessiles/Downloads/Documents.GAP/GAPProjects/myproject/project.tests.cypress/node_modules/mochawesome-merge/lib/index.js:14:11
    at Array.map (<anonymous>)
    at /Users/moisessiles/Downloads/Documents.GAP/GAPProjects/myproject/project.tests.cypress/node_modules/mochawesome-merge/lib/utils.js:3:46
    at merge (/Users/moisessiles/Downloads/Documents.GAP/GAPProjects/myproject/project.tests.cypress/node_modules/mochawesome-merge/lib/index.js:82:17)
    at generateReport (/Users/moisessiles/Downloads/Documents.GAP/GAPProjects/myproject/project.tests.cypress/node_modules/@0xislamtaha/orchestrator/src/orchestrator.js:224:10)
    at afterPromises (/Users/moisessiles/Downloads/Documents.GAP/GAPProjects/myproject/project.tests.cypress/node_modules/@0xislamtaha/orchestrator/src/orchestrator.js:257:3)
    at /Users/moisessiles/Downloads/Documents.GAP/GAPProjects/myproject/project.tests.cypress/node_modules/@0xislamtaha/orchestrator/src/orchestrator.js:279:7
```
And I tried with the slash at the end

```
Can't run because no spec files were found.

We searched for any files matching this glob pattern:

src/integration/navigation/page-classes

Relative to the project root folder:

/orechestrator_usecase
Can't run because no spec files were found.

We searched for any files matching this glob pattern:

src/integration/navigation/tests

Relative to the project root folder:
```

**Comment by 0xIslamTaha** [comment]
> @0xIslamTaha I have updated the regex with `existingSpecs = sh.ls('-R', config.specsHomePath).filter((val) => val.match(/^.*\.spec\.(ts|js)$/));`
> 
> I was trying to create the PR but what should be the process,
> 
> 1. Clone the repo
> 2. Create a new branch using the ticket #
> 3. Push the changes (Currently I'm stuck here because I couldn't push my changes due to permissions issues)
> 4. Send the PR

That seems good to me too, but I'm not sure why u can't push. Can you share with me the error message? 

@msilesgap

**Comment by 0xIslamTaha** [comment]
@msilesgap 
I have two questions:
- Did u mange to install V 1.1.1? if yes, Do u still have the same issue?
- Did u clone the repo using the HTML link? or how did u clone it?

**Comment by msilesgap** [comment]
Thanks @0xIslamTaha I'll open the tickets and also I gonna review the code and see if I can help with some of them. Thanks for your help.
